### ISSUE TITLE
grrm2rmap

### ISSUE THREAD

**Issue by shiroco** [ReactionMap/RMapViewer#4]
Hi, I had a problem when converting the output files from GRRM to rmapfiles with grrm2rmap. The number of generated structures is small (5 structures in total) but the size of the molecule is rather large (113 atoms). The process was automatically "killed" after these messages were output.
---
  5 molecules converted
  140 audit log messages
  Killed: 9
---
Does the converter have a limitation of the molecular size or did this happen due to any other reasons?

**Comment by tomooda** [comment]
Fixed now.
https://raw.githubusercontent.com/ReactionMap/RMapViewer/master/scripts/grrm2rmap

grrm2rmap failed to parse SDF files when a molecule have more then 99 atoms. Because SDF format prints atom id in 3 chars, two atom ids are printed without a separator. This fix is just a quick hack. I keep this issue open until I'll make a real fix.

**Comment by shiroco** [comment]
Now it works. Thank you very much. Yes, SDF is a classical format. The max number of atom is 999.
